### ISSUE TITLE
App Crash on SQLite cursor

### ISSUE THREAD

**Issue by philippb** [amplitude/Amplitude-Android#19]
Amplitude version: `com.amplitude:android-sdk:1.3`

Stack Trace
_________________________________
```
0	android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
1		at android.database.CursorWindow.<init>(CursorWindow.java:108)
2		at android.database.CursorWindow.<init>(CursorWindow.java:100)
3		at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
4		at android.database.sqlite.SQLiteCursor.clearOrCreateWindow(SQLiteCursor.java:301)
5		at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
6		at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
7		at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
8		at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
9		at com.amplitude.api.DatabaseHelper.getEvents(Unknown Source)
10		at com.amplitude.api.Amplitude.updateServer(Unknown Source)
11		at com.amplitude.api.Amplitude.updateServer(Unknown Source)
12		at com.amplitude.api.Amplitude.access$100(Unknown Source)
13		at com.amplitude.api.Amplitude$3.run(Unknown Source)
14		at android.os.Handler.handleCallback(Handler.java:733)
15		at android.os.Handler.dispatchMessage(Handler.java:95)
16		at android.os.Looper.loop(Looper.java:157)
17		at android.os.HandlerThread.run(HandlerThread.java:61)

```

**Comment by allanca** [comment]
Thanks for reporting this.

I've been investigating the crash and though I've been unable to reproduce, I have a few theories about possible causes.

It looks like it occurred on Android 5.0. Do you have any other information about the conditions at the time of the crash? Device type? When in the application lifecycle?

**Comment by allanca** [comment]
Fixed in release 1.4.4 on 3/11.

**Comment by xiphirx** [comment]
Still exists on v1.6.2,

Device types:
![image](https://cloud.githubusercontent.com/assets/993832/7528014/354dbb96-f4d7-11e4-840f-29e61f967872.png)

Android versions:
![image](https://cloud.githubusercontent.com/assets/993832/7528016/3f519450-f4d7-11e4-9375-778c90af93ed.png)

```
0	android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed.
1	at android.database.CursorWindow.<init>(CursorWindow.java:109)
2	at android.database.CursorWindow.<init>(CursorWindow.java:100)
3	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
4	at android.database.sqlite.SQLiteCursor.clearOrCreateWindow(SQLiteCursor.java:301)
5	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
6	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
7	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
8	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
9	at com.amplitude.api.DatabaseHelper.getEvents(DatabaseHelper.java:91)
10	at com.amplitude.api.AmplitudeClient.updateServer(AmplitudeClient.java:594)
11	at com.amplitude.api.AmplitudeClient.updateServer(AmplitudeClient.java:582)
12	at com.amplitude.api.AmplitudeClient.access$1400(AmplitudeClient.java:31)
13	at com.amplitude.api.AmplitudeClient$4.run(AmplitudeClient.java:343)
14	at android.os.Handler.handleCallback(Handler.java:733)
15	at android.os.Handler.dispatchMessage(Handler.java:95)
16	at android.os.Looper.loop(Looper.java:136)
17	at android.os.HandlerThread.run(HandlerThread.java:61)
```
